// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKw7YdLsUg5YNtHR_GCVryZJnuUezatPc',
    appId: '1:1734546993:web:cde2b6db22422ea32ca710',
    messagingSenderId: '1734546993',
    projectId: 'mybookswappapp',
    authDomain: 'mybookswappapp.firebaseapp.com',
    storageBucket: 'mybookswappapp.firebasestorage.app',
    measurementId: 'G-33NJNE8Z59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsevcOj5wXPVkQyoqhk1mk7sj4Zet226o',
    appId: '1:1734546993:android:a3384f855d3e0ad12ca710',
    messagingSenderId: '1734546993',
    projectId: 'mybookswappapp',
    storageBucket: 'mybookswappapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqH5UsmOcFK7vbWWZhGrlRErMhPUslz6o',
    appId: '1:1734546993:ios:74a5205f3d627f3d2ca710',
    messagingSenderId: '1734546993',
    projectId: 'mybookswappapp',
    storageBucket: 'mybookswappapp.firebasestorage.app',
    iosClientId: '1734546993-o1k1taj1gdjnfidd5pno4qjteds7dssn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqH5UsmOcFK7vbWWZhGrlRErMhPUslz6o',
    appId: '1:1734546993:ios:74a5205f3d627f3d2ca710',
    messagingSenderId: '1734546993',
    projectId: 'mybookswappapp',
    storageBucket: 'mybookswappapp.firebasestorage.app',
    iosClientId: '1734546993-o1k1taj1gdjnfidd5pno4qjteds7dssn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKw7YdLsUg5YNtHR_GCVryZJnuUezatPc',
    appId: '1:1734546993:web:7a9e044dc92e03c12ca710',
    messagingSenderId: '1734546993',
    projectId: 'mybookswappapp',
    authDomain: 'mybookswappapp.firebaseapp.com',
    storageBucket: 'mybookswappapp.firebasestorage.app',
    measurementId: 'G-FQYY12SXVF',
  );

}